//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LOGIN
    {
        public string COD_LOGIN { get; set; }
        public string COD_TIPO_LOG { get; set; }
        public string C_USER { get; set; }
        public string C_PASSWORD { get; set; }
    
        public virtual TIPO_LOGIN TIPO_LOGIN { get; set; }
    }
}
