//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERIALES()
        {
            this.DETALLE_ORDEN_ATENCION = new HashSet<DETALLE_ORDEN_ATENCION>();
            this.ORDEN_COMPRA = new HashSet<ORDEN_COMPRA>();
            this.REGISTRAR_SERVICIO = new HashSet<REGISTRAR_SERVICIO>();
        }
    
        public string COD_MATE { get; set; }
        public string COD_MARCA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> PRECI_UNI { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
    
        public virtual MARCA_MATERIAL MARCA_MATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ORDEN_ATENCION> DETALLE_ORDEN_ATENCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRAR_SERVICIO> REGISTRAR_SERVICIO { get; set; }
    }
}
