//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA
    {
        public string COD_MATE { get; set; }
        public int RUC { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
    
        public virtual MATERIALES MATERIALES { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
