//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRAR_SERVICIO
    {
        public string COD_MATE { get; set; }
        public string COD_SERVICIO { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual MATERIALES MATERIALES { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
